version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql_network

# persist mysql to /var/lib/mysql
volumes:
  mysql_data:

# define network so mysql can communicate with service
networks:
  mysql_network:
